/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import { useGLTF } from "@react-three/drei"
import axeUrl from "./assets/axe.glb"
import pickUrl from "./assets/pick.glb"

export default function Axe(props) {
  const { nodes, materials } = useGLTF(pickUrl)
  // const { nodes, materials } = useGLTF(axeUrl)
  console.log(nodes)
  console.log(materials)
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, 0.2]} scale={0.018}>
        <mesh geometry={nodes.Object_2.geometry} material={materials["Material.009"]} />
        {/* <mesh geometry={nodes.Mesh_1001_2.geometry} material={materials.material_3} /> */}
      </group>
    </group>
  )
}

useGLTF.preload("/pick.glb")
